create table sandbox.agency_trackers (
  id uuid not null default gen_random_uuid (),
  agency_id uuid not null,
  member_name text not null,
  latitude double precision null,
  longitude double precision null,
  last_updated timestamp with time zone null,
  tracking_status text null default 'Offline'::text,
  created_at timestamp with time zone not null default now(),
  constraint agency_trackers_pkey primary key (id),
  constraint agency_trackers_agency_id_fkey foreign KEY (agency_id) references sandbox.jpbd_directory (id)
) TABLESPACE pg_default;

create table sandbox.angkatan_categories (
  id integer not null default nextval('angkatan_categories_id_seq'::regclass),
  name text null,
  count integer null,
  color text null,
  constraint angkatan_categories_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.angkatan_community (
  id integer not null default nextval('angkatan_community_id_seq'::regclass),
  category text null,
  label text null,
  detail text null,
  color text null,
  constraint angkatan_community_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.angkatan_pyramid (
  id integer not null default nextval('angkatan_pyramid_id_seq'::regclass),
  rank text null,
  total integer null,
  color text null,
  display_order integer null,
  constraint angkatan_pyramid_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.angkatan_ranks (
  id integer not null default nextval('angkatan_ranks_id_seq'::regclass),
  rank text null,
  lulus integer null,
  kenaikan integer null,
  kbp integer null,
  ptb integer null,
  aktif integer null,
  simpanan integer null,
  constraint angkatan_ranks_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.angkatan_summary (
  id integer not null,
  total_anggota integer null,
  aktif_anggota integer null,
  male_count integer null,
  female_count integer null,
  status_lulus integer null,
  status_lantikan integer null,
  status_simpanan integer null,
  status_aktif integer null,
  constraint angkatan_summary_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.calamity_points (
  id uuid not null default gen_random_uuid (),
  category text not null,
  description text null,
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamp with time zone not null default now(),
  constraint calamity_points_pkey primary key (id),
  constraint calamity_points_category_check check (
    (
      category = any (
        array[
          'KJR'::text,
          'KM'::text,
          'MMS'::text,
          'KBD'::text,
          'KK'::text,
          'SKT'::text,
          'KTK'::text,
          'PT'::text,
          'KBR'::text,
          'ML'::text,
          'LLK'::text,
          'KB'::text,
          'MHL'::text,
          'MHP'::text,
          'MT'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table sandbox.home_data (
  id integer not null,
  data_json jsonb not null,
  constraint home_data_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.hotspots (
  id uuid not null default gen_random_uuid (),
  category text not null,
  river text not null,
  area text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  ref_no text null,
  constraint hotspots_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.jpbd_directory (
  id uuid not null default gen_random_uuid (),
  agency text not null,
  officer text null,
  position text null,
  grade text null,
  email text null,
  address text null,
  office_phone text null,
  mobile_phone text null,
  fax text null,
  officers_count text null,
  members_count text null,
  logistics_assets text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint jpbd_directory_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.kewangan_breakdown (
  id bigint generated by default as identity not null,
  q text not null,
  months text not null,
  spend text not null,
  color text null default '#3b82f6'::text,
  created_at timestamp with time zone null default now(),
  constraint kewangan_breakdown_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.kewangan_budget (
  id bigint generated by default as identity not null,
  kategori text not null,
  perihal text not null,
  agihan numeric(15, 2) null default 0.00,
  belanja numeric(15, 2) null default 0.00,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint kewangan_budget_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.kewangan_summary (
  id integer not null,
  title text null,
  year text null,
  total_allocation numeric(15, 2) not null default 0,
  constraint kewangan_summary_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.laporan_ng999 (
  id uuid not null default gen_random_uuid (),
  kategori_kes text not null,
  month text not null,
  created_at timestamp with time zone null default now(),
  jumlah_kes integer null default 1,
  constraint laporan_ng999_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.latihan (
  id uuid not null default gen_random_uuid (),
  title text not null,
  pax integer null default 0,
  status text null default 'Tidak Berjaya'::text,
  note text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  start_date date null,
  end_date date null,
  constraint latihan_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.logistik (
  id uuid not null default gen_random_uuid (),
  category text not null,
  type text not null,
  model text not null,
  reg text null,
  qty integer null,
  status text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  nota_selenggara text null,
  latitude double precision null,
  longitude double precision null,
  tracking_status text null default 'Idle'::text,
  color text null default '#ef4444'::text,
  last_updated timestamp with time zone null,
  constraint logistik_pkey primary key (id),
  constraint logistik_category_check check (
    (
      category = any (array['Darat'::text, 'Laut'::text])
    )
  ),
  constraint logistik_status_check check (
    (
      status = any (
        array['Baik'::text, 'Selenggara'::text, 'Rosak'::text]
      )
    )
  )
) TABLESPACE pg_default;

create table sandbox.pentadbiran_data (
  id integer not null,
  data_json jsonb null,
  constraint pentadbiran_data_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.pps_list (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  name text not null,
  zone text null,
  type text not null,
  capacity integer null default 0,
  status text null default 'OK'::text,
  constraint pps_list_pkey primary key (id),
  constraint pps_list_type_check check (
    (
      type = any (
        array[
          'Dewan'::text,
          'Sekolah/Kolej'::text,
          'Balairaya'::text,
          'Lain-Lain'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table sandbox.profiles (
  id uuid not null,
  username text not null,
  role text not null default 'user'::text,
  agency_id uuid null,
  latitude double precision null,
  longitude double precision null,
  last_updated timestamp with time zone null,
  tracking_status text null default 'Offline'::text,
  constraint profiles_pkey primary key (id),
  constraint profiles_username_key unique (username),
  constraint profiles_agency_id_fkey foreign KEY (agency_id) references sandbox.jpbd_directory (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table sandbox.save_snapshots (
  id serial not null,
  save_id integer not null,
  data_json jsonb not null,
  pdf_url text null,
  created_at timestamp with time zone not null default now(),
  constraint save_snapshots_pkey primary key (id),
  constraint save_snapshots_save_id_fkey foreign KEY (save_id) references sandbox.saves (id) on delete CASCADE
) TABLESPACE pg_default;

create table sandbox.saves (
  id serial not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  constraint saves_pkey primary key (id)
) TABLESPACE pg_default;

create table sandbox.vehicles (
  id uuid not null default gen_random_uuid (),
  name text not null,
  type text not null,
  status text null default 'Active'::text,
  latitude double precision null,
  longitude double precision null,
  last_updated timestamp with time zone null default now(),
  color text null,
  constraint vehicles_pkey primary key (id)
) TABLESPACE pg_default;