create table public.angkatan_categories (
  id serial not null,
  name text null,
  count integer null,
  color text null,
  constraint angkatan_categories_pkey primary key (id)
) TABLESPACE pg_default;

create table public.angkatan_community (
  id serial not null,
  category text null,
  label text null,
  detail text null,
  color text null,
  constraint angkatan_community_pkey primary key (id)
) TABLESPACE pg_default;

create table public.angkatan_pyramid (
  id serial not null,
  rank text null,
  total integer null,
  color text null,
  display_order integer null,
  constraint angkatan_pyramid_pkey primary key (id)
) TABLESPACE pg_default;

create table public.angkatan_ranks (
  id serial not null,
  rank text null,
  lulus integer null,
  kenaikan integer null,
  kbp integer null,
  ptb integer null,
  aktif integer null,
  simpanan integer null,
  constraint angkatan_ranks_pkey primary key (id)
) TABLESPACE pg_default;

create table public.angkatan_summary (
  id integer not null,
  total_anggota integer null,
  aktif_anggota integer null,
  male_count integer null,
  female_count integer null,
  status_lulus integer null,
  status_lantikan integer null,
  status_simpanan integer null,
  status_aktif integer null,
  constraint angkatan_summary_pkey primary key (id)
) TABLESPACE pg_default;

create table public.home_data (
  id integer not null,
  data_json jsonb not null,
  constraint home_data_pkey primary key (id)
) TABLESPACE pg_default;

create table public.hotspots (
  id uuid not null default gen_random_uuid (),
  category text not null,
  river text not null,
  area text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  ref_no text null,
  constraint hotspots_pkey primary key (id)
) TABLESPACE pg_default;

create table public.jpbd_directory (
  id uuid not null default gen_random_uuid (),
  agency text not null,
  officer text null,
  position text null,
  grade text null,
  email text null,
  address text null,
  office_phone text null,
  mobile_phone text null,
  fax text null,
  officers_count text null,
  members_count text null,
  logistics_assets text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint jpbd_directory_pkey primary key (id)
) TABLESPACE pg_default;

create table public.kewangan_breakdown (
  id bigint generated by default as identity not null,
  q text not null,
  months text not null,
  spend text not null,
  color text null default '#3b82f6'::text,
  created_at timestamp with time zone null default now(),
  constraint kewangan_breakdown_pkey primary key (id)
) TABLESPACE pg_default;

create table public.kewangan_budget (
  id bigint generated by default as identity not null,
  kategori text not null,
  perihal text not null,
  agihan numeric(15, 2) null default 0.00,
  belanja numeric(15, 2) null default 0.00,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint kewangan_budget_pkey primary key (id)
) TABLESPACE pg_default;

create table public.laporan_ng999 (
  id uuid not null default gen_random_uuid (),
  kategori_kes text not null,
  month text not null,
  created_at timestamp with time zone null default now(),
  jumlah_kes integer null default 1,
  constraint laporan_ng999_pkey primary key (id)
) TABLESPACE pg_default;

create table public.latihan (
  id uuid not null default gen_random_uuid (),
  title text not null,
  pax integer null default 0,
  status text null default 'Tidak Berjaya'::text,
  note text null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  start_date date null,
  end_date date null,
  constraint latihan_pkey primary key (id)
) TABLESPACE pg_default;

create table public.logistik (
  id uuid not null default gen_random_uuid (),
  category text not null,
  type text not null,
  model text not null,
  reg text null,
  qty integer null,
  status text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  nota_selenggara text null,
  latitude double precision null,
  longitude double precision null,
  tracking_status text null default 'Idle'::text,
  color text null default '#ef4444'::text,
  last_updated timestamp with time zone null,
  constraint logistik_pkey primary key (id),
  constraint logistik_category_check check (
    (
      category = any (array['Darat'::text, 'Laut'::text])
    )
  ),
  constraint logistik_status_check check (
    (
      status = any (
        array['Baik'::text, 'Selenggara'::text, 'Rosak'::text]
      )
    )
  )
) TABLESPACE pg_default;

create table public.pentadbiran_data (
  id integer not null,
  data_json jsonb null,
  constraint pentadbiran_data_pkey primary key (id)
) TABLESPACE pg_default;

create table public.pps_list (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  name text not null,
  zone text null,
  type text not null,
  capacity integer null default 0,
  status text null default 'OK'::text,
  constraint pps_list_pkey primary key (id),
  constraint pps_list_type_check check (
    (
      type = any (
        array[
          'Dewan'::text,
          'Sekolah/Kolej'::text,
          'Balairaya'::text,
          'Lain-Lain'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.profiles (
  id uuid not null,
  username text not null,
  role text not null default 'user'::text,
  constraint profiles_pkey primary key (id),
  constraint profiles_username_key unique (username),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.vehicles (
  id uuid not null default gen_random_uuid (),
  name text not null,
  type text not null,
  status text null default 'Active'::text,
  latitude double precision null,
  longitude double precision null,
  last_updated timestamp with time zone null default now(),
  color text null,
  constraint vehicles_pkey primary key (id)
) TABLESPACE pg_default;

// History
create or replace function close_cycle(p_cycle_id integer)
returns void as $$
declare
  v_snapshot jsonb;
begin
  select jsonb_build_object(
    'angkatan_categories', (select jsonb_agg(t) from angkatan_categories t),
    'angkatan_community', (select jsonb_agg(t) from angkatan_community t),
    'angkatan_pyramid', (select jsonb_agg(t) from angkatan_pyramid t),
    'angkatan_ranks', (select jsonb_agg(t) from angkatan_ranks t),
    'angkatan_summary', (select jsonb_agg(t) from angkatan_summary t),
    'home_data', (select jsonb_agg(t) from home_data t),
    'hotspots', (select jsonb_agg(t) from hotspots t),
    'jpbd_directory', (select jsonb_agg(t) from jpbd_directory t),
    'kewangan_breakdown', (select jsonb_agg(t) from kewangan_breakdown t),
    'kewangan_budget', (select jsonb_agg(t) from kewangan_budget t),
    'laporan_ng999', (select jsonb_agg(t) from laporan_ng999 t),
    'latihan', (select jsonb_agg(t) from latihan t),
    'logistik', (select jsonb_agg(t) from logistik t),
    'pentadbiran_data', (select jsonb_agg(t) from pentadbiran_data t),
    'pps_list', (select jsonb_agg(t) from pps_list t),
    'vehicles', (select jsonb_agg(t) from vehicles t)
  ) into v_snapshot;

  insert into cycle_archives (cycle_id, data_json)
  values (p_cycle_id, v_snapshot);

  update cycles
  set status = 'closed', closed_at = now()
  where id = p_cycle_id;
end;
$$ language plpgsql;