// src/screens/operasi/mapStyles.js
import { StyleSheet } from 'react-native';
import { PALETTE } from '../../constants/palette';

export const mapStyles = StyleSheet.create({
  container: { position: 'relative', width: '100%', overflow: 'hidden', borderRadius: 24, paddingBottom: 16 },
  toggleWrapper: { flexDirection: 'row', margin: 16, padding: 6, borderRadius: 16, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 5, elevation: 3, zIndex: 20 },
  toggleBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 12, gap: 8 },
  toggleBtnActive: { backgroundColor: '#3b82f6' },
  toggleText: { fontSize: 13, fontWeight: '700' },
  toggleTextActive: { color: '#fff' },
  viewContainer: { flex: 1, flexDirection: 'row', position: 'relative', marginHorizontal: 16, marginTop: 16, borderRadius: 20, overflow: 'hidden' },
  viewContainerMobile: { flexDirection: 'column', overflow: 'visible' },
  mapContainer: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 0 },

  historyToggleBtn: {
    position: 'absolute', top: 16, right: 116, zIndex: 10,
    width: 40, height: 40, borderRadius: 12, backgroundColor: '#fff',
    justifyContent: 'center', alignItems: 'center',
    shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10, elevation: 4,
  },
  summaryToggleBtn: {
    position: 'absolute', top: 16, right: 164, zIndex: 10,
    width: 40, height: 40, borderRadius: 12, backgroundColor: '#fff',
    justifyContent: 'center', alignItems: 'center',
    shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10, elevation: 4,
  },
  historyTooltip: {
    position: 'absolute', top: 46, right: 0, zIndex: 20,
    backgroundColor: '#0f172a', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8,
  },
  historyTooltipText: { color: '#fff', fontSize: 11, fontWeight: '700' },
  panelCloseBtn: { width: 28, height: 28, borderRadius: 6, backgroundColor: '#f1f5f9', justifyContent: 'center', alignItems: 'center' },
  calamityPalette: {
    position: 'absolute', top: 16, right: 16, zIndex: 10, backgroundColor: '#fff',
    borderRadius: 16, padding: 10, gap: 6, shadowColor: '#000', shadowOpacity: 0.1,
    shadowRadius: 10, elevation: 4, width: 90,
  },
  calamityPaletteMobile: { width: 60, padding: 6, gap: 4, borderRadius: 12 },
  calamityToolBtn: { paddingVertical: 8, borderRadius: 8, borderWidth: 2, justifyContent: 'center', alignItems: 'center', marginBottom: 6 },
  calamityToolBtnMobile: { paddingVertical: 5, borderRadius: 6, borderWidth: 1.5, marginBottom: 4 },
  calamityToolText: { fontSize: 11, fontWeight: '800' },
  calamityToolTextMobile: { fontSize: 9 },
  calamityHint: { fontSize: 10, color: '#64748b', textAlign: 'center', marginTop: 4 },

  historyHalf: { flex: 1, backgroundColor: '#fff', borderLeftWidth: 1, borderLeftColor: '#e2e8f0' },
  historyHalfMobile: { flex: 1, borderLeftWidth: 0 },
  historyHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  pdfExportBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: PALETTE.orange, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, minWidth: 60, justifyContent: 'center' },
  pdfExportBtnDisabled: { backgroundColor: '#cbd5e1' },
  pdfExportBtnText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  historyTitle: { fontSize: 14, fontWeight: '800', color: '#0f172a' },
  historyFilterRow: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, paddingTop: 12, paddingBottom: 4, zIndex: 50 },

  calamityTableWrapper: { borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, overflow: 'hidden', marginHorizontal: 16 },
  calamityTableHeaderRow: { flexDirection: 'row', backgroundColor: '#1E3A8A' },
  calamityHeaderCellBox: { alignItems: 'center', justifyContent: 'center', paddingVertical: 14, paddingHorizontal: 6, gap: 5 },
  calamityTableHeaderCell: { fontSize: 13, fontWeight: '800', color: '#fff', textAlign: 'center' },
  calamityTableRow: { flexDirection: 'row', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#f1f5f9' },
  calamityTableCell: { fontSize: 14, color: '#334155', textAlign: 'center', paddingVertical: 14, paddingHorizontal: 6 },
  calamityMonthColFlex: { flex: 2, paddingLeft: 15 },
  historyKenderaanColFlex: { flex: 2 },
  calamityCatColFlex: { flex: 1 },
  calamitySummaryCellBox: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  calamityTotalColFlex: { flex: 1.2, alignItems: 'center', justifyContent: 'center', paddingVertical: 14 },
  routeColFlex: { flex: 0.8 },
  routeBtn: { width: 32, height: 32, borderRadius: 8, backgroundColor: '#eff6ff', justifyContent: 'center', alignItems: 'center' },
  routeBtnActive: { backgroundColor: '#1E3A8A' },
  calamityTotalBadge: {},
  calamityCumulativeRow: { backgroundColor: '#fef3c7' },
  calamityTotalBadgeText: { fontSize: 15, fontWeight: '900', color: '#1E3A8A' },
  summaryChartWrapper: { marginTop: 16, marginBottom: 8, backgroundColor: '#fff', borderRadius: 12, borderWidth: 1, borderColor: '#e2e8f0', padding: 20, position: 'relative', overflow: 'hidden' },  
  chartCatChip: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, borderWidth: 1.5 },
  chartCatChipText: { fontSize: 10, fontWeight: '800' },
  summaryChartTitle: { fontSize: 12, fontWeight: '800', color: '#0f172a', marginBottom: 8 },

  waypointPanel: { paddingHorizontal: 20, paddingVertical: 10, backgroundColor: '#f8fafc', borderTopWidth: 1, borderTopColor: '#e2e8f0' },
  waypointRow: { paddingVertical: 6, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  waypointLabel: { fontSize: 12, fontWeight: '700', color: '#0f172a' },
  waypointDetail: { fontSize: 11, color: '#64748b', marginTop: 2 },
  waypointEmptyText: { fontSize: 12, color: '#94a3b8', fontStyle: 'italic', textAlign: 'center', paddingVertical: 8 },

  tableCellAgency: { fontSize: 13, fontWeight: '800', color: '#0f172a', textAlign: 'left' },
  abandonedBadge: { backgroundColor: '#fef3c7', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  abandonedBadgeText: { fontSize: 9, fontWeight: '700', color: '#92400e' },
  tableCellMember: { fontSize: 11, color: '#64748b', marginTop: 1, textAlign: 'left' },
  tableCellDate: { fontSize: 11, fontWeight: '700', color: '#334155', textAlign: 'left' },
  tableCellTime: { fontSize: 10, color: '#94a3b8', marginTop: 1, textAlign: 'left' },

  historyCardMobile: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 12, padding: 12, marginBottom: 10, marginHorizontal: 16 },
  historyCardMobileTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 10 },
  historyCardMobileStatsRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  historyCardMobileStat: { fontSize: 12, fontWeight: '600', color: '#475569' },
  historyCardMobileStatDivider: { fontSize: 12, color: '#cbd5e1' },

  paginationRow: { alignItems: 'center', paddingVertical: 12, borderTopWidth: 1, borderTopColor: '#f1f5f9', gap: 8 },
  pageArrowRow: { flexDirection: 'row', gap: 10 },
  pageBtn: { width: 36, height: 36, borderRadius: 8, backgroundColor: '#eff6ff', justifyContent: 'center', alignItems: 'center' },
  pageBtnDisabled: { backgroundColor: '#f1f5f9' },
  pageBtnText: { fontSize: 16, fontWeight: '700', color: '#1E3A8A' },
  pageBtnTextDisabled: { color: '#cbd5e1' },
  pageIndicator: { fontSize: 12, fontWeight: '700', color: '#64748b' },

  loader: { ...StyleSheet.absoluteFillObject, justifyContent: 'center', alignItems: 'center', zIndex: 2 },
  headerCard: { position: 'absolute', top: 16, left: 16, zIndex: 10, flexDirection: 'row', alignItems: 'center', padding: 16, borderRadius: 16, gap: 12, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 10, elevation: 4, minWidth: 200 },
  iconCircle: { width: 40, height: 40, borderRadius: 12, backgroundColor: '#ef4444', justifyContent: 'center', alignItems: 'center' },
  headerTitle: { fontSize: 16, fontWeight: '800' },
  liveTagContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 4, gap: 6 },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#22c55e' },
  liveText: { fontSize: 10, fontWeight: '700' },
  vehicleListContainer: { position: 'absolute', bottom: 16, left: 16, right: 16, zIndex: 10 },
});